# Title of your homepage
title: TUoS HPC Changelog #(required)

# Website Description for search engines (optional)
description: "Keep yourself up to date with recent changes on the University of Sheffield HPC clusters."

# replace this word in navigation bar. Ex: Productnews, ChangeLog, Updates
heading: Updates # (optional)

# absolute or relative path of logo
logo: /assets/img/Tuos-Logo.jpg #(required)

# Your Product's Website
website: https://docs.hpc.shef.ac.uk/en/latest/ # (required)

# the base hostname & protocol for your site, 
# e.g. https://updates.changelog.site
# Note Don't put trailing slash https://updates.changelog.site/
url: "https://rcgsheffield.github.io"  # (required)

baseurl: '/hpc-changelog' # optional


# Github username/repo where your code is hosted.
github: rcgsheffield/hpc-changelog # (required)

# remove this line if don't want to show Github Star Badge
star-badge: true  #(optional)

# remove this line if don't want to show Github Watch Badge
watch-badge: true #(optional)

# Show rss feed icon in menubar. To disable this comment below line by adding # as first character.
rss-feed-icon: true #(optional)

# Global site tag (gtag.js) - Google Analytics e.g. UA-MYANALYTICS
#analytics:  #(recommended)

# https://changelog-site.disqus.com
# disqus-identifier: changelog-site  # (optional)

# Allow users to comment via facebook
fb-comment: true

# Allow search engines to index your changelog website
allow-searchengine: true #optional


# Do not change anything below this if you don't know Jekyll

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets"
    values:
      sitemap: false 

collections:
  tags:
    output: true
    permalink: tags/:path/


permalink: /:title/
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-remote-theme
  
remote_theme: jonaharagon/jekyll-bootstrap-theme

pagination:
  enabled: true
  per_page: 5
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
