name: build site with jekyll

on:
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  jekyll:
    runs-on: ubuntu-20.04 #
    steps:
      # checkout code
      - uses: actions/checkout@v4

      # Use ruby/setup-ruby to shorten build times
      # https://github.com/ruby/setup-ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      # use jekyll-action-ts to build
      # https://github.com/limjh16/jekyll-action-ts
      - uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
